version: "3.9"
services:
  back:
    build: Back-End/
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
  front:
    build: Front-End/
    stdin_open: true
    tty: true
    ports:
      - "3001:3000"
    


volumes:
  logvolume01: {}